# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Alex Figueroa
description: A WIP collection of technical ramblings and photographs
markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://alexjfigueroa.com'
google_analytics: 'UA-76173192-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://alexjfigueroa.com'
author:         'Alex Figueroa'

# User Settings
profile_image_url: 'http://www.gravatar.com/avatar/ecbaec4f458de7172daff03e1f20e677'
twitter_username: externvar
github_username: ajfigueroa
